### ISSUE TITLE
Link to the github repo somewhere

### ISSUE THREAD

**Issue by kasbah** [monostable/kitnic#31]

**Comment by kasbah** [comment]
Maybe next to the submit link and use the GH logo from octicons?

**Comment by kasbah** [comment]
Also see #21 to update the submit link.

**Comment by kasbah** [comment]
Maybe this could be a "Fork me on GitHub" banner in the bottom left.

http://jessy1092.github.io/react-github-fork-ribbon/

**Comment by slifin** [comment]
The text for the Register a project button is mis-aligned in firefox 
Add a grey button style for the contribute to Kitnic text

Let's see if we can get mobile looking more respectable by decreasing font-size of Register a project and decreasing size of logo on mobile

**Comment by slifin** [comment]
The branch has been updated with the above requirements
