### ISSUE TITLE
Title line spacing issue in mobile view

### ISSUE THREAD

**Issue by kasbah** [monostable/kitnic#35]
![screen shot 2016-05-05 at 13 37 10](https://cloud.githubusercontent.com/assets/206854/15043651/ab3a2d04-12c6-11e6-8029-d6793dc74f62.png)

**Comment by slifin** [comment]
I'm having trouble replicating this
what device/browser did you use to replicate this? 

Mobile Firefox (Nexus 5)
![image](https://cloud.githubusercontent.com/assets/198857/15071994/b7ae98ce-1387-11e6-9abf-1e6e2a98670a.png)
Mobile Chrome (Nexus 5)
![image](https://cloud.githubusercontent.com/assets/198857/15072024/e7cc4e3e-1387-11e6-8c3c-e80351773ab6.png)
iphone 5 (emulated) 
![image](https://cloud.githubusercontent.com/assets/198857/15072066/4ba13a6e-1388-11e6-9aab-691a38d6ed45.png)
other emulated devices yield similar results

**Comment by kasbah** [comment]
Firefox responsive design mode with a width less than 480 or so. 
![kitnic_mobile_title](https://cloud.githubusercontent.com/assets/206854/15073295/baab3704-1390-11e6-8b04-95829f32408a.png)
