### ISSUE TITLE
Graphics issues in Opera

### ISSUE THREAD

**Issue by kasbah** [monostable/kitnic#64]
https://saucelabs.com/beta/tests/34db96409a694e0086bb51d8661da393

Alignment in titlebar is off

![0002screenshot](https://cloud.githubusercontent.com/assets/206854/15277092/c5fab590-1af1-11e6-97d7-099a91226ddc.png)

SVGs don't appear on main page and size of Mouser icon is wrong.

![0003screenshot](https://cloud.githubusercontent.com/assets/206854/15277102/f535e85c-1af1-11e6-8de4-2f101d9fd24e.png)

**Comment by slifin** [comment]
Are you sure you want me to try and get Opera 12/11 rendering correctly? 
For reference the current version of Opera is 37 and runs on a different rendering engine

**Comment by kasbah** [comment]
Ah, I wasn't aware. Should briefly test a recent Opera though.

**Comment by slifin** [comment]
Yeah I took a look on OSX yesterday everything seems good there on Opera, I assume this is because Chrome and Opera share blink as a rendering engine

Here is a screenshot of windows: 

![image](https://cloud.githubusercontent.com/assets/198857/15389555/7405d6e6-1daf-11e6-9917-b64fb9745e5a.png)

**Comment by kasbah** [comment]
cool
